name: luxnova
favicon: null
layout_spectrum: 0.8852073464076966
typography_spectrum: 0.23037478257901967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6692845381330699
  lightness: 0.19991255039349198
  saturation: 0.4784239251166582
  rhythmicContrast: 0.765911131631583
purpose: []
